// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRestLogging.Database;

namespace WebApiRestLogging.Migrations
{
    [DbContext(typeof(GroceryContext))]
    [Migration("20201025183620_DataLoader")]
    partial class DataLoader
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiRestLogging.Models.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Groceries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Aggregator",
                            DateCreated = new DateTime(2020, 10, 25, 18, 36, 20, 354, DateTimeKind.Utc).AddTicks(5297),
                            Department = "Perishable",
                            Description = "Hunt's Tomato Paste, 6 oz",
                            Name = "Hunt's Tomato Paste",
                            Quantity = 3,
                            UnitPrice = 0.49m
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Forwarder",
                            DateCreated = new DateTime(2020, 10, 25, 18, 36, 20, 354, DateTimeKind.Utc).AddTicks(6677),
                            Department = "Produce",
                            Description = "Ripe plantains",
                            Name = "Plantains",
                            Quantity = 8,
                            UnitPrice = 0.79m
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2020, 10, 25, 18, 36, 20, 354, DateTimeKind.Utc).AddTicks(6706),
                            Department = "Refreshments",
                            Description = "Heineken lager",
                            Name = "12 Pack Beer",
                            Quantity = 1,
                            UnitPrice = 14.49m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
